env:
  browser: true
  node: true
  mocha: true
  es6: true
parser: 'babel-eslint'
parserOptions:
  sourceType: module
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always